---
- name: Add a user
  hosts: all
  vars_prompt:

    - name: username
      prompt: "username:"
      private: false

    - name: uid
      prompt: "uid: (int)"
      private: false

  tasks:

  - name: Create a new user group
    ansible.builtin.group:
      name: "{{ username }}"
      gid: "{{ uid | int }}"
      state: present 

  - name: Create user account
    ansible.builtin.user:
      name: "{{ username }}"
      uid: "{{ uid | int }}"
      group: "{{ username }}"
      home: "/mnt/nfs/home/{{ username }}"
      state: present
